Hyrax your luck 2.9.1
WGBH-MLA/ams pull request #495
Opened 2020-10-28 19:46 UTC by foglabs

Adds Video JS files
Changes `representative_media` partial to use video js
Adds 'anonymous' crossorigin option to video element to handle cors.

2020-10-28 20:28 UTC, afred requested changes

2020-10-28 20:28 UTC, afred commented on package.json
> +    "react-iiif-media-player": "2.0.0",
i think we don't need this anymore, right?

2020-10-28 20:28 UTC, afred commented on app/views/hyrax/assets/_representative_media.html.erb
> +  Not playable
I just thew "Not playable" in there as a placeholder. Can include the media type to provide more of a clue?
```
Not playable: unrecognized media type: "<%= media type %>".
```

2020-11-02 20:13 UTC, foglabs commented
*somehow, not someone

2020-11-12 15:24 UTC, merged