585 handle sony ci webhook
WGBH-MLA/ams pull request #597
Opened 2021-07-20 17:38 UTC by afred

2021-07-21 16:43 UTC, foglabs requested changes
I think the things I tagged are a copy paste error, but otherwise looks 👍

2021-07-21 17:03 UTC, afred commented on app/controllers/sony_ci/webhook_logs_controller.rb
> +        format.json { render :show, status: :ok, location: @sony_ci_webhook_log }
Ack... i meant to get rid of all actions pertaining to WebhookLogs that were not `#show` or `#index`. The `WebhgookLog` records get created by virtue of Sony Ci sending requests to the `/webhooks/[action]` endpoint(s), so we don't currently have a use case for adding/editing/deleting the `WebhookLog` records directly. I'll fix this.

fwiw, you're correct, I think those actions responding with `format.json` will try to render a `app/views/sony_ci/webhook_logs/[action].json.jbuilder`, which is a ruby file that uses a ruby DSL to build JSON structures from `ActiveRecord` models. I believe I removed the tests for these controller actions, hence no errors on Travis.

2021-07-21 17:14 UTC, foglabs approved these changes

2021-07-23 20:36 UTC, afred commented
NOTE: the branch name beginning in `585` is misleading here, this PR is a solution for #584, not 585.

2021-07-26 17:39 UTC, afred commented
and finally, in lieu of Travis buids...
![image](https://user-images.githubusercontent.com/1507490/127033919-d4eb5918-6107-4ced-a28a-7ce3f1eab5fc.png)

2021-07-27 20:30 UTC, merged