I60 specs destroy local data bug
WGBH-MLA/ams pull request #753
Opened 2023-08-12 00:50 UTC by ShanaLMoore

2023-08-12 02:22 UTC, ShanaLMoore commented
@orangewolf @aprilrieger I would appreciate a review of this, from a devops perspective. I'm not confident about my changes besides the fact that its no longer destroying my development data when I run a spec 🎉

2023-08-14 19:57 UTC, ShanaLMoore commented
Switching to Draft. It's ready for review but I don't want anyone to accidentally merge it until devops review.

2023-08-15 22:15 UTC, ShanaLMoore commented on .solr_wrapper
> +
revert - we aren't using solr_wrapper

2023-08-15 22:15 UTC, ShanaLMoore commented on config/solr_wrapper_test.yml
> +
revert

2023-08-15 22:15 UTC, ShanaLMoore commented on docker-compose.yml
> +      - SOLR_ADMIN_USERNAME=solr
Don't need

2023-08-15 22:15 UTC, orangewolf commented on docker-compose.yml
> +      - SOLR_ADMIN_USERNAME=solr
these dont do anything

2023-08-15 22:16 UTC, orangewolf commented on .solr_wrapper
> +
revert since we dont use this

2023-08-15 22:16 UTC, orangewolf commented on config/fedora.yml
> +  url: <%= ENV['FCREPO_URL'] || "http://127.0.0.1:8983/fedora/rest" %>
un-needed change

2023-08-15 22:16 UTC, orangewolf commented on config/solr_wrapper_test.yml
> +
revert since we cant test it

2023-08-15 22:17 UTC, orangewolf requested changes
remove stuff unrelated to this fix. the fix looks great though.

2023-08-16 17:56 UTC, orangewolf approved these changes

2023-08-16 17:56 UTC, merged