I24 dual boot support ci
WGBH-MLA/ams pull request #755
Opened 2023-08-14 16:37 UTC by ShanaLMoore

WIP

ref: https://github.com/scientist-softserv/ams/issues/24

2023-08-15 22:22 UTC, orangewolf requested changes

2023-08-15 22:22 UTC, orangewolf commented on docker-compose.yml
> +      - SOLR_ENABLE_AUTHENTICATION=yes
these are unneeded

2023-08-16 04:14 UTC, orangewolf approved these changes
excellent work!

2023-08-16 04:14 UTC, merged

2023-08-16 14:32 UTC, ShanaLMoore commented
@orangewolf we just noticed that something is still not right with this work. 

We expect 10 failures to be reported from the rails 6 context. 

We can see that rails 6 isn't using the correct gem versions. For example, hyrda-access-controls should be 12.0.1 as seen when running the rails 6 specs locally (and as stated in the Gemfile_next.lock file). 

![image (24)](https://github.com/WGBH-MLA/ams/assets/10081604/b2c970dc-b4ca-4d01-8f1f-17d72b564fd0)

However, all the specs are passing in the rails 6 build and it's using production gem versions: 

<img width="963" alt="image" src="https://github.com/WGBH-MLA/ams/assets/10081604/c10de1fd-b18b-4216-9dc3-c9576d046acb">